### PR TITLE
macos support

### PR DESCRIPTION
**Pull request by JonnycatMeow**
yessir made it from scratch

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]
cool 👍

**Comment by JonnycatMeow** [comment]
Screen Shot 2023-02-04 at 6 21 45 PM
don't worry about the warning's they don't do shit

**Comment by JonnycatMeow** [comment]
Screen Shot 2023-02-04 at 6 22 22 PM
it works

**Comment by moxie-coder** [comment]
btw @JonnycatMeow this is my new github

**Comment by JonnycatMeow** [comment]
@MemeHovy nice

**Comment by EliteMasterEric** [comment]
Accepted

**Comment by BushTrain460615** [comment]
Stole what I made and said he made it from scratch

**Pull request merged**
